DROP TABLE IF EXISTS TV_SHOWS;

CREATE TABLE TV_SHOWS (
  id BIGINT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  image_url VARCHAR(250) NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE EPISODES(
  id BIGINT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  season INT NOT NULL,
  number INT NOT NULL,
  airDate DATE NOT NULL,
  watched BOOLEAN,
  tv_show_id BIGINT FOREIGN KEY (tv_show_id) REFERENCES TV_SHOWS(ID)
);

CREATE TABLE CAST_LIST(
  id BIGINT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  image_url VARCHAR(250) NOT NULL,
  tv_show_id BIGINT FOREIGN KEY (tv_show_id) REFERENCES TV_SHOWS(ID)
);